### ISSUE TITLE
trouble with gdal in orson

### ISSUE THREAD

**Issue by jmigueldelgado** [jmigueldelgado/buhayra#20]
```
Traceback (most recent call last):
  File "/users/stud09/martinsd/local/miniconda2/envs/snappy6/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/users/stud09/martinsd/local/miniconda2/envs/snappy6/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/users/stud09/martinsd/proj/buhayra/__main__.py", line 72, in <module>
    main()
  File "/users/stud09/martinsd/proj/buhayra/__main__.py", line 24, in main
    import sar2watermask.sar as sar
  File "/users/stud09/martinsd/proj/buhayra/sar2watermask/sar.py", line 22, in <module>
    import fiona
  File "/users/stud09/martinsd/local/miniconda2/envs/snappy6/lib/python2.7/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/users/stud09/martinsd/local/miniconda2/envs/snappy6/lib/python2.7/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: /users/stud09/martinsd/local/miniconda2/envs/snappy6/lib/python2.7/site-packages/fiona/../../../libgdal.so.20: undefined symbol: _ZN9kmlengine4Href5ParseERKSs
```

**Comment by jmigueldelgado** [comment]
no apparent solution for this. I am now trying to do a fresh install  of jpy and reconfigure snappy to work with python 3.6

check this for building jpy: https://github.com/bcdev/jpy#how-to-build-on-linux-and-mac

**Comment by jmigueldelgado** [comment]
on my personal computer a solution is:
- install python 3.6 and maven in a new env
- build jpy wheel
-cp jpy wheel to snappy config
- config snappy and install remaining modules (rasterio, fiona, shapely, pyproj)
