### ISSUE TITLE
run time error in thermal noise removal

### ISSUE THREAD

**Issue by jmigueldelgado** [jmigueldelgado/buhayra#27]
java.lang.NullPointerException
Traceback (most recent call last):
  File "/users/stud09/martinsd/local/miniconda2/envs/buhayra/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/users/stud09/martinsd/local/miniconda2/envs/buhayra/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/users/stud09/martinsd/proj/buhayra/__main__.py", line 101, in <module>
    main()
  File "/users/stud09/martinsd/proj/buhayra/__main__.py", line 48, in main
    sar.sar2sigma(f)
  File "/users/stud09/martinsd/proj/buhayra/sar2watermask/sar.py", line 296, in sar2sigma
    product_oc_tn=thermal_noise_removal(product_oc)
  File "/users/stud09/martinsd/proj/buhayra/sar2watermask/sar.py", line 201, in thermal_noise_removal
    result = GPF.createProduct('ThermalNoiseRemoval',params,product)
RuntimeError: org.esa.snap.core.gpf.OperatorException: java.lang.NullPointerException

**Comment by jmigueldelgado** [comment]
running in gpt
