### ISSUE TITLE
threshold

### ISSUE THREAD

**Issue by jmigueldelgado** [jmigueldelgado/buhayra#29]
Traceback (most recent call last):
  File "rasterio/_base.pyx", line 199, in rasterio._base.DatasetBase.__init__
  File "rasterio/_shim.pyx", line 64, in rasterio._shim.open_dataset
  File "rasterio/_err.pyx", line 194, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_NotSupportedError: Scanline/tile/strip size bigger than 2GB.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/stud09/martinsd/local/miniconda2/envs/buhayra/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/users/stud09/martinsd/local/miniconda2/envs/buhayra/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/users/stud09/martinsd/proj/buhayra/__main__.py", line 125, in <module>
    main()
  File "/users/stud09/martinsd/proj/buhayra/__main__.py", line 66, in main
    thresh.threshold_loop(scenes)
  File "/users/stud09/martinsd/proj/buhayra/buhayra/thresholding.py", line 20, in threshold_loop
    with rasterio.open(sarOut+'/'+f,'r') as ds:
  File "/users/stud09/martinsd/local/miniconda2/envs/buhayra/lib/python3.6/site-packages/rasterio/env.py", line 398, in wrapper
    return f(*args, **kwds)
  File "/users/stud09/martinsd/local/miniconda2/envs/buhayra/lib/python3.6/site-packages/rasterio/__init__.py", line 217, in open
    s = DatasetReader(path, driver=driver, **kwargs)
  File "rasterio/_base.pyx", line 201, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: Scanline/tile/strip size bigger than 2GB.

**Comment by jmigueldelgado** [comment]
This can be solved upstream by saving outpup of sar.py in `big tiff`
